// Hardcoded locality/area mappings for major Indian cities
// Used for filtering wellness places by locality

export const CITY_LOCALITIES: Record<string, string[]> = {
  'Mumbai': [
    'Bandra',
    'Powai',
    'Andheri',
    'Colaba',
    'Dadar',
    'Fort',
    'Marine Drive',
    'Malad',
    'Vile Parle',
    'Borivali',
    'Thane',
    'Navi Mumbai',
  ],
  'Delhi': [
    'Connaught Place',
    'Dwarka',
    'Mayur Vihar',
    'Noida',
    'Gurgaon',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'North Delhi',
    'Indirapuram',
  ],
  'Bangalore': [
    'Indiranagar',
    'Koramangala',
    'Whitefield',
    'MG Road',
    'Jayanagar',
    'Malleswaram',
    'Marathahalli',
    'Yeshwanthpur',
    'Bellandur',
    'Electronic City',
    'Vijayanagar',
  ],
  'Hyderabad': [
    'Banjara Hills',
    'Jubilee Hills',
    'Secunderabad',
    'HITEC City',
    'Madhapur',
    'Begumpet',
    'Kukatpally',
    'Chanderghat',
    'Hitech City',
    'Gachibowli',
  ],
  'Ahmedabad': [
    'Ahmedabad',
    'Navrangpura',
    'Satellite',
    'Thaltej',
    'Science City',
    'Vastrapur',
    'Ramdev Nagar',
    'Moti Nagar',
    'Iscon Ambli',
    'Keshav Nagar',
    'Bopal',
  ],
  'Chennai': [
    'T Nagar',
    'Anna Nagar',
    'Velachery',
    'Mylapore',
    'Adyar',
    'Nungambakkam',
    'Egmore',
    'Guindy',
    'Porur',
    'Sholinganallur',
  ],
  'Kolkata': [
    'Ballygunge',
    'Salt Lake',
    'Alipore',
    'Park Circus',
    'Jadavpur',
    'Dhakuria',
    'Howrah',
    'Dum Dum',
    'Baranagar',
    'Belgachia',
  ],
  'Pune': [
    'Koregaon Park',
    'Baner',
    'Viman Nagar',
    'Kalyani Nagar',
    'Kothrud',
    'Shivaji Nagar',
    'Model Colony',
    'Aundh',
    'Hadapsar',
    'Kharadi',
  ],
  'Jaipur': [
    'C-Scheme',
    'M.I. Road',
    'Malviya Nagar',
    'Vaishali Nagar',
    'Mansarovar',
    'Sanganer',
    'Sodala',
    'Raja Park',
    'Civil Lines',
    'Amer',
  ],
  'Lucknow': [
    'Alambagh',
    'Gomti Nagar',
    'Indira Nagar',
    'Charbagh',
    'Hazratganj',
    'Aliganj',
    'Vibhuti Khand',
    'LDA Colony',
    'Nishatganj',
    'Belgaum',
  ],
  'Chandigarh': [
    'Sector 17',
    'Sector 35',
    'Sector 22',
    'Sector 8',
    'Sector 9',
    'Sector 10',
    'Sector 12',
    'Sector 26',
    'Sector 31',
  ],
  'Indore': [
    'Rajwada',
    'Sarwate',
    'Bhanwarkunj',
    'Palasia',
    'South Tukoganj',
    'Sudama Nagar',
    'Vijay Nagar',
  ],
  'Visakhapatnam': [
    'Dwarakanagar',
    'Gajuwaka',
    'Ameerpet',
    'CBD',
    'Kakinada',
    'MVP Colony',
    'Old Town',
  ],
  'Surat': [
    'Althan',
    'Vesu',
    'Umarwada',
    'Adajan',
    'Piplod',
    'Varachha',
    'Katargam',
  ],
  'Kochi': [
    'Kochi',
    'Ernakulathappan',
    'Mattancherry',
    'Fort Kochi',
    'Kakkanad',
  ],
};

// Get localities for a given city
export const getLocalitiesForCity = (city: string): string[] => {
  return CITY_LOCALITIES[city] || [];
};

// Get all cities
export const getAllCities = (): string[] => {
  return Object.keys(CITY_LOCALITIES);
};
